# Generated by Django 3.2.7 on 2022-01-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Bill payment', '1'), ('Withdrawal', '2'), ('Commissions', '3'), ('Transfers', '4'), ('Airtime/Data', '5'), ('FX Transactions', '6'), ('Others', '7'), ('Salaries & wages', '8'), ('Interest & Dividends', '9')], default='Bill payment', max_length=25)),
                ('sub_category', models.CharField(choices=[('Food', '1'), ('Internet Services', '2'), ('Shopping', '5'), ('Cash Withdrawal', '7'), ('ATM Withdrawal', '8'), ('Web Transactions', '12')], default='Food', max_length=25)),
                ('description', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
            ],
        ),
    ]
